name:                InvasiveSpecies
version:             0.1.0.0
github:              "yanfrimmels/InvasiveSpecies"
license:             BSD3
author:              "Yan Frimmel"
maintainer:          "yan.frimmel1411@gmail.com"
copyright:           "2019 Yan Frimmel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/InvasiveSpecies#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- reflex >= 0.5 && < 0.6
- reflex-sdl2
- sdl2-image
- sdl2-ttf
- text

library:
  source-dirs: src

executables:
  InvasiveSpecies-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InvasiveSpecies

tests:
  InvasiveSpecies-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InvasiveSpecies
